### ISSUE TITLE
Dataset Download

### ISSUE THREAD

**Issue by patpatera** [jeffreychou777/LOTVS-MMAU#1]
Hi there,

Would you, please, consider to re-upload your dataset on different international website? Such as Google Drive or others? 
Pan.baidu is not available for most of the countries outside China. It makes unable to obtain for future research.

**Comment by jeffreychou777** [comment]
Hi，
Thank you for your attention and feedback, we will upload the data to more sites like **google drive** as soon as possible! Please stay tuned.

**Comment by saunair** [comment]
Hi @jeffreychou777 it seems like the original link is down. Would it be possible to upload this to google-drive or dropbox?

**Comment by patpatera** [comment]
@jeffreychou777  It has been over a month since you mentioned uploading to another site (e.g. Google Drive). What is the progress? If you have published a novel benchmark dataset at an international conference such as CVPR, you should also make it available for other researchers outside of China.

**Comment by jeffreychou777** [comment]
Hi,
Thanks for your attention to our work!
I apologize that we have not been able to complete the uploading of the dataset to google drive at this time due to busy schedules, huge volume of data, unstable networks, and non-universal payment methods.

I have the following two suggestions：
1. you can leave an email address so that I can notify you first after completing the google drive upload.
2. Seek the help of Chinese people around you who are overseas, they can complete the download of BaiDuNetDisk data.

**Comment by IceIce1ce** [comment]
Hi authors,

First of all, congratulations on your paper which was published as a highlight paper at CVPR 2024. I want to know when you can release fully the code and the drive link of the dataset that were used in your paper?

**Comment by jeffreychou777** [comment]
Hi Tran,
Thanks for your attention, we have released the code for abductive_clip, its in the benchmark for video_diffusion. Once we get permission from the lab, we will re-upload the data, and we will keep working on the google drive link uploads.

> Hi authors,
> 
> First of all, congratulations on your paper which was published as a highlight paper at CVPR 2024. I want to know when you can release fully the code and the drive link of the dataset that were used in your paper?

**Comment by jeffreychou777** [comment]
Hi, guys
We have uploaded the raw datasets to the huggingface datasets repo:[LinK](https://huggingface.co/datasets/JeffreyChou/MM-AU/tree/main)
Sorry this took so long, thanks for the attention！
