### ISSUE TITLE
about datatset

### ISSUE THREAD

**Issue by Mogalipen** [jeffreychou777/LOTVS-MMAU#2]
Hi~
請問有考慮增加物件追蹤的label嗎?

**Comment by jeffreychou777** [comment]
Hi～
你好，感謝你的關註。
MM-AU數據集在標註時並沒有對目標跟蹤（Object Tracking）任務進行標記。如果你需要使用MM-AU數據集進行目標跟蹤任務，可以考慮使用訓練好的跟蹤模型對數據集進行推理，將推理結果當作跟蹤任務的偽標簽。

**Comment by Mogalipen** [comment]
那請問若要訓練是否車禍的模型，是否有其他的物件偵測資料集可做為負樣本呢?
或是有其他更好的方式能夠達成嗎?
因為MMAU的物件偵測標籤是6fps，而BDD100k是5fps
期待您的回覆，萬分感謝~

**Comment by jeffreychou777** [comment]
在MM-AU數據集中t_ai之前的視頻序列可以當作負樣本，bdd100k、hevi、bdda等正常駕駛數據集也都可以用作負樣本。
