### ISSUE TITLE
About raw video download

### ISSUE THREAD

**Issue by zhousheng97** [jeffreychou777/LOTVS-MMAU#3]
Hello, according to the Baidu Netdisk link you provided, I found that it only contains video frames. Could you please provide the download link for the original video?

**Comment by jeffreychou777** [comment]
Thank you for your attention to our project!
There is no raw original video format like .mp4 or .mov. You can try to composite video using frames by opencv if you need the video of mp4 format.

**Comment by zhousheng97** [comment]
> Thank you for your attention to our project! There is no raw original video format like .mp4 or .mov. You can try to composite video using frames by opencv if you need the video of mp4 format.

Thanks for your reply, I will use the images provided to synthesize the video.
